### ISSUE TITLE
Links would be helpful

### ISSUE THREAD

**Issue by ensslen** [MicrosoftDocs/BingAds-docs#163]
The example doesn't build without ExampleBase from BingAdsExamplesLibrary.V11. https://github.com/BingAds/BingAds-dotNet-SDK/blob/master/examples/BingAdsExamples/BingAdsExamplesLibrary/ExampleBase.cs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d28f3fd3-080f-7a07-2d8d-bb084c25be07
* Version Independent ID: a90f0b68-95e3-dee9-c7b8-93848885e1ba
* Content: [Search User Accounts Code Example - Bing Ads | Microsoft Docs](https://docs.microsoft.com/en-us/bingads/guides/code-example-search-user-accounts?view=bingads-11)
* Content Source: [BingAds/bingads-11/guides/code-example-search-user-accounts.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/live/BingAds/bingads-11/guides/code-example-search-user-accounts.md)
* Service: **bing-ads**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@ensslen thanks for the feedback! We are now adding a note about the dependencies to the top of each example.
