### ISSUE TITLE
Auto-approval of sandbox store does not work.

### ISSUE THREAD

**Issue by hravnaas** [MicrosoftDocs/BingAds-docs#188]
The above described auto-approval of a sandbox store does not appear to work. My store was rejected a few hours after first being created. I had to contact support to have them manually approve it. Please update the documentation or auto-approval process. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2118670f-af2b-9f6d-f0b2-b5a089c11489
* Version Independent ID: ed2a84af-e79a-f632-16c7-95fa6458eea3
* Content: [Bing Ads Sandbox - Bing Ads](https://docs.microsoft.com/en-us/bingads/guides/sandbox?view=bingads-11#productads)
* Content Source: [BingAds/bingads-11/guides/sandbox.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/live/BingAds/bingads-11/guides/sandbox.md)
* Service: **bing-ads**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@hravnaas thanks for reporting this issue. I am waiting for an update from our engineers. Thanks for your patience.

**Comment by eric-urban** [comment]
@hravnaas this issue should now be resolved i.e., the auto approval should work as documented. Thanks again!

**Comment by hravnaas** [comment]
Thank you, Eric!
