### ISSUE TITLE
Example doesn't compile

### ISSUE THREAD

**Issue by ensslen** [MicrosoftDocs/BingAds-docs#191]
In order to get this to compile with .Net 4.5 in Visual Studio 2013 on Server 2008R2 I had to
1. Add "using System.Net.Http;"
2. Replace all 4 occurrences of "Microsoft.BingAds" with "Microsoft.BingAds.V11"
3. Change line 286 to specify that "Paging" is "Microsoft.BingAds.V11.CustomerManagement.Paging"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 621c29d1-e0b0-7d28-5ed5-48c2a0e4b6d3
* Version Independent ID: 12bd38c6-f315-bb24-6f8f-1969083c0ab4
* Content: [Walkthrough: Bing Ads Desktop Application in C# - Bing Ads](https://docs.microsoft.com/en-us/bingads/guides/walkthrough-desktop-application-csharp?view=bingads-11)
* Content Source: [BingAds/bingads-11/guides/walkthrough-desktop-application-csharp.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/live/BingAds/bingads-11/guides/walkthrough-desktop-application-csharp.md)
* Service: **bing-ads**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@ensslen we will fix it ASAP. Thanks!

**Comment by eric-urban** [comment]
@ensslen  the doc has been updated. Thanks again.
