### ISSUE TITLE
v12 SDK availability Github?

### ISSUE THREAD

**Issue by CIS-python** [MicrosoftDocs/BingAds-docs#196]
When will the v12 SDKs officially be pushed to GitHub?  Currently v11.5.9 is listed as the most recent version for each language of the SDKs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3228ff4-34ac-a0b7-7091-f74212715a84
* Version Independent ID: dd837296-c1d9-6b03-d661-55112b5288bb
* Content: [Get Started Using Python with Bing Ads Services - Bing Ads](https://docs.microsoft.com/en-us/bingads/guides/get-started-python?view=bingads-12)
* Content Source: [BingAds/bingads-12/guides/get-started-python.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/live/BingAds/bingads-12/guides/get-started-python.md)
* Service: **bing-ads**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@CIS-python coming soon! Will update and close this issue once v12 support is added.

**Comment by eric-urban** [comment]
@CIS-python all Bing Ads SDKs now support v12.
