### ISSUE TITLE
Required Columns Incorrect

### ISSUE THREAD

**Issue by C-Saunders** [MicrosoftDocs/BingAds-docs#210]
As of May 1, 2018, the Required Columns section of this page is incorrect, based on my testing. You'll need to include DynamicAdTarget in your request.

I'm not sure if there are other undocumented required columns since I stopped testing when I got my download to work by adding DynamicAdTarget to the columns I requested.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 621adccd-81dd-81a3-c238-4373514a4e0f
* Version Independent ID: 428f739a-66a1-420e-7d47-8dede379425c
* Content: [DSAAutoTargetPerformanceReportColumn Value Set - Reporting - Bing Ads](https://docs.microsoft.com/en-us/bingads/reporting-service/dsaautotargetperformancereportcolumn?view=bingads-11)
* Content Source: [BingAds/bingads-11/reporting-service/dsaautotargetperformancereportcolumn.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/live/BingAds/bingads-11/reporting-service/dsaautotargetperformancereportcolumn.md)
* Service: **bing-ads-reporting-service**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@C-Saunders thanks for the heads up! I tested today and confirmed that DynamicAdTarget (not DynamicAdTargetId) is required. We will update the doc.

**Comment by C-Saunders** [comment]
@eric-urban I had no idea I was opening an issue when I submitted this feedback- this is super cool. Thanks for your response!

**Comment by eric-urban** [comment]
@C-Saunders the doc is updated, so I'll close this issue. Thanks again for the feedback!
