### ISSUE TITLE
Where do I find the actual GeoLocation csv file?

### ISSUE THREAD

**Issue by bhavsi** [MicrosoftDocs/BingAds-docs#220]
I have been looking around and end up on this page, but I am unable to find the actual csv file that I can download (manually, not through API), and take a look at the Geo Locations. Where can I download the csv?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28816aa9-de1d-ab0d-5b8a-ff920a148566
* Version Independent ID: c622fe8a-b289-5fff-48ab-f261b95adb1c
* Content: [Geographical Location Codes - Bing Ads](https://docs.microsoft.com/en-us/bingads/guides/geographical-location-codes?view=bingads-12)
* Content Source: [BingAds/bingads-12/guides/geographical-location-codes.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/live/BingAds/bingads-12/guides/geographical-location-codes.md)
* Service: **bing-ads**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@bhavsi you can download via the [FileUrl](https://docs.microsoft.com/en-us/bingads/campaign-management-service/getgeolocationsfileurl?view=bingads-12#fileurl) provided in the response from the GetGeoLocationsFileUrl operation. You can also download the data without using the API from the [Bing Ads Developer Portal](https://developers.azure.bingads.microsoft.com/Account). You must be signed in to the developer portal with a Microsoft account user who has Bing Ads credentials.
