### ISSUE TITLE
CallAdExtensions "CountryCode" is documented incorrectly

### ISSUE THREAD

**Issue by rsuddeth** [MicrosoftDocs/BingAds-docs#222]
Is says (correctly) that CountryCode should be a 2 character country code. But instead of referring to a list of country codes, it gives this link: https://docs.microsoft.com/en-us/bingads/guides/geographical-location-codes?view=bingads-11, which is something completely different.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b044c5d-2cdf-d261-75b0-fe0c70690339
* Version Independent ID: 002238fe-01bf-4f70-fa68-613fd8a1a4c1
* Content: [CallAdExtension Data Object - Campaign Management - Bing Ads](https://docs.microsoft.com/en-us/bingads/campaign-management-service/calladextension?view=bingads-11)
* Content Source: [BingAds/bingads-11/campaign-management-service/calladextension.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/live/BingAds/bingads-11/campaign-management-service/calladextension.md)
* Service: **bing-ads-campaign-management-service**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@rsuddeth thanks for flagging this issue. Previously the country code were provided in the geo locations file, but as you observed they are no longer available. We will update the documentation ASAP with the supported codes.

**Comment by eric-urban** [comment]
@rsuddeth the doc is updated. Thanks again.
