### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by tobyberesford** [MicrosoftDocs/BingAds-docs#236]
It would be really useful here to have a Getting started path that just used the Developer Token to query Bing Ads API. I'm trying to use the Management Model for Direct Advertisers so an Oauth walkthrough is of limited use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5819ecf-4666-9f16-b735-64bd65610bdb
* Version Independent ID: 5b66a562-2c4b-a5fc-b8ed-ffaf6ad43c73
* Content: [Walkthrough: Bing Ads Web Application in PHP - Bing Ads](https://docs.microsoft.com/en-us/bingads/guides/walkthrough-web-application-php?view=bingads-12)
* Content Source: [BingAds/bingads-12/guides/walkthrough-web-application-php.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/live/BingAds/bingads-12/guides/walkthrough-web-application-php.md)
* Service: **bing-ads**
* Product: **unspecified**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@tobyberesford it isn't possible to use the Bing Ads API with only a DeveloperToken. You must authenticate with credentials of a user who has access to a Bing Ads account. Starting in version 12 OAuth is required. I'm reviewing your other feedback now, and will reply to each. Thanks!
