### ISSUE TITLE
No hello world?

### ISSUE THREAD

**Issue by tobyberesford** [MicrosoftDocs/BingAds-docs#237]
This all feels a bit too much like starting in the deep end.  Is there a very basic hello world example you can show? e.g.

```
include these libraries

this is how you auth with dev token and sandbox

this is a command to get a list of your bing ads campaigns

print the list of campaigns 

that's it :)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d21d434-14da-534f-fa59-d4d9c19a61f4
* Version Independent ID: 054f3fcb-8b77-8515-a031-618eaa44db7c
* Content: [Get Started Using PHP with Bing Ads Services - Bing Ads](https://docs.microsoft.com/en-us/bingads/guides/get-started-php?view=bingads-12)
* Content Source: [BingAds/bingads-12/guides/get-started-php.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/live/BingAds/bingads-12/guides/get-started-php.md)
* Service: **bing-ads**
* Product: **unspecified**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@tobyberesford for PHP I suggest starting with [this walkthrough](https://docs.microsoft.com/en-us/bingads/guides/walkthrough-desktop-application-php?view=bingads-12). Please reach out if you have any further feedback or questions about it.
