### ISSUE TITLE
Filter by PHP

### ISSUE THREAD

**Issue by tobyberesford** [MicrosoftDocs/BingAds-docs#240]
Please can you add a filter to this page so I can filter just the samples that have PHP examples. Saves me having to click into each to find out if there is a PHP version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b23cbfe-7ffc-7388-2c5d-3ed2f7e64e92
* Version Independent ID: 4ecfc61f-c2f0-7425-fd15-0971b1cfc43f
* Content: [Bing Ads Code Examples - Bing Ads](https://docs.microsoft.com/en-us/bingads/guides/code-examples?view=bingads-12)
* Content Source: [BingAds/bingads-12/guides/code-examples.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/live/BingAds/bingads-12/guides/code-examples.md)
* Service: **bing-ads**
* Product: **unspecified**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@tobyberesford this is good feedback, thanks. We've added a column to indicate available languages per sample. Most of the samples are now available in C#, Java, Php, and Python, with very few exceptions.
