### ISSUE TITLE
I don't have a converged applications option

### ISSUE THREAD

**Issue by tobyberesford** [MicrosoftDocs/BingAds-docs#243]
Heya, are the create application steps out of date? The screenshot shows "converged applications" but I just have "my applications". Maybe I need to create more different types of applications to get that screen?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1be06e0b-96b2-b624-0ddf-e4773824b09e
* Version Independent ID: 092386a6-320f-3b7c-3781-b9f0417dc399
* Content: [Authentication with OAuth - Bing Ads](https://docs.microsoft.com/en-us/bingads/guides/authentication-oauth?view=bingads-12#feedback)
* Content Source: [BingAds/bingads-12/guides/authentication-oauth.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/live/BingAds/bingads-12/guides/authentication-oauth.md)
* Service: **bing-ads**
* Product: **unspecified**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@tobyberesford good feedback, thanks. Bing Ads API devs who have been around several years will still see the Converged applications vs Live SDK applications. As you noted, newer clients will not. To ease on-boarding we'll update the doc with a screen shot that shows the new client experience, and add a note explaining "converged vs Live SDK" that will still be observed by some clients.

**Comment by eric-urban** [comment]
@tobyberesford the doc is updated with new screen shot, etc. Thanks again!
