### ISSUE TITLE
A Gotcha to watch out for

### ISSUE THREAD

**Issue by tobyberesford** [MicrosoftDocs/BingAds-docs#244]
One gotcha to watch out for is to make sure your registered application is configured to support the "native application" platform. :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1bc63d1-9a2f-8428-5176-7b2faf6ab80e
* Version Independent ID: cdfa6e4f-a83c-4b20-1c35-77a72c61d348
* Content: [Walkthrough: Bing Ads Desktop Application in PHP - Bing Ads](https://docs.microsoft.com/en-us/bingads/guides/walkthrough-desktop-application-php?view=bingads-12)
* Content Source: [BingAds/bingads-12/guides/walkthrough-desktop-application-php.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/live/BingAds/bingads-12/guides/walkthrough-desktop-application-php.md)
* Service: **bing-ads**
* Product: **unspecified**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@tobyberesford what specific error did you observe? Either Web or Native should work. If you plan to eventually deploy as a console or background task on a remote service such as Azure, you might register the web platform with a client secret and you could even use that web app ID with the "desktop" sample e.g., just to get the initial refresh token.

**Comment by tobyberesford** [comment]
You're right! I've now removed the native platform from my app and it works fine, so I can't reproduce the problem.
