### ISSUE TITLE
bing shoping-content 500 Server Error: Internal Server Error

### ISSUE THREAD

**Issue by micaliu153** [MicrosoftDocs/BingAds-docs#249]
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://content.api.bingads.microsoft.com/shopping/v9.1/bmc/***/products/batch

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b877c29-9521-3269-f072-7764b375e0c7
* Version Independent ID: 7dafcd81-b075-7007-d9e2-0db48b80ce6c
* Content: [Products Resource - Bing Ads](https://docs.microsoft.com/en-us/bingads/shopping-content/products-resource#feedback)
* Content Source: [BingAds/shopping-content/products-resource.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/live/BingAds/shopping-content/products-resource.md)
* Service: **shopping-content-api**
* Product: **unspecified**
* GitHub Login: @swhite-msft
* Microsoft Alias: **scottwhi**

**Comment by swhite-msft** [comment]
Hello @micaliu153. 500 server errors are typically transient. If you continue to receive them, please contact Bing Ads support and provide them the WebRequestActivityId header from your response, so they can track down the issue. Thanks
