### ISSUE TITLE
Class name in comment would not compile

### ISSUE THREAD

**Issue by codecadwallader** [MicrosoftDocs/BingAds-docs#256]
There's a commented out example above:

// Alternatively you can request data for a subset of campaigns or ad groups.
               //Scope = new AccountThroughAdGroupReportScope
               //{
               //    AccountIds = null,
               //    Campaigns = new[] {
               //         new AdGroupReportScope
               //         {
               //             AccountId = accountId,
               //             CampaignId = &lt;YourCampaignIdGoesHere&gt;,
               //             AdGroupId = &lt;YourAdGroupIdGoesHere&gt;
               //         }
               //    }
               //},

However an AdGroupReportScope cannot be assigned to Campaigns.. this should be CampaignReportScope.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 663008b6-1280-9ad2-7f46-94b12b531920
* Version Independent ID: b679e12f-a226-d24b-d24e-92ff8a26bf66
* Content: [Report Requests Code Example - Bing Ads](https://docs.microsoft.com/en-us/bingads/guides/code-example-report-requests?view=bingads-12)
* Content Source: [BingAds/bingads-12/guides/code-example-report-requests.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/live/BingAds/bingads-12/guides/code-example-report-requests.md)
* Service: **bing-ads**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by codecadwallader** [comment]
or on further thought.. perhaps its intended to be assigned to AdGroupReports (instead of Campaigns).  In that case the class name is right, its what the array is being assigned to that needs updated.

**Comment by codecadwallader** [comment]
In other words..
//  AdGroups = new[] {
//  new AdGroupReportScope

**Comment by eric-urban** [comment]
@codecadwallader good catch thanks! Looks like a copy/paste error with the commented out code (compile didn't catch it). We've updated the sample in the [SDK repository](https://github.com/BingAds/BingAds-dotNet-SDK/blob/master/examples/BingAdsExamples/BingAdsExamplesLibrary/v12/ReportRequests.cs#L432), and will update Docs next opportunity.

**Comment by codecadwallader** [comment]
Looks good, thanks for the quick turnaround!
