### ISSUE TITLE
Incorrect

### ISSUE THREAD

**Issue by gregroberts** [MicrosoftDocs/BingAds-docs#275]
The python examples for this doc are for version 11.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d27a6323-8dbe-f47d-7534-ed6351ec32c2
* Version Independent ID: 60714b2c-dbd3-2ffc-b954-6c54004ca22c
* Content: [Reporting Service Manager - Bing Ads](https://docs.microsoft.com/en-us/bingads/guides/sdk-reporting-service-manager?view=bingads-12)
* Content Source: [BingAds/bingads-12/guides/sdk-reporting-service-manager.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/live/BingAds/bingads-12/guides/sdk-reporting-service-manager.md)
* Service: **bing-ads**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@gregroberts thanks for letting us know. The update is checked in and should be live soon.
