### ISSUE TITLE
Table at bottom of the page isn't displaying properly.

### ISSUE THREAD

**Issue by benm-brainlabs** [MicrosoftDocs/BingAds-docs#292]
The table at the bottom of the page is just displaying as text.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f1f207d-a78f-038d-4536-2b5f46613e92
* Version Independent ID: 1b59be2d-37a8-6215-67bd-78cc573c9bce
* Content: [Bing Ads Scripts Errors and Warnings - Bing Ads](https://docs.microsoft.com/en-us/bingads/scripts/concepts/errors-and-warnings)
* Content Source: [BingAds/scripts/concepts/errors-and-warnings.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/live/BingAds/scripts/concepts/errors-and-warnings.md)
* Service: **bingads-scripts**
* GitHub Login: @brapel
* Microsoft Alias: **v-brapel**

**Comment by swhite-msft** [comment]
We'll get it fixed today. Thanks a lot for letting us know!
