### ISSUE TITLE
Add API Call Limits

### ISSUE THREAD

**Issue by noerjeffries** [MicrosoftDocs/BingAds-docs#333]
Where can I find information about API call limits? I'm getting the following error:

AdApiError Code: 117 Error Code: CallRateExceeded Message: You have exceeded the number of calls that you are allowed to make in a minute. Please reduce the number of calls that you make per minute.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 235f7820-534e-f27b-e74b-656ffbcb5e9b
* Version Independent ID: ab4c6a90-d0d9-25f4-65e6-49bd4575ce9e
* Content: [Frequently Asked Questions - Bing Ads](https://docs.microsoft.com/en-us/bingads/guides/faq?view=bingads-12)
* Content Source: [BingAds/bingads-12/guides/faq.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/live/BingAds/bingads-12/guides/faq.md)
* Service: **bing-ads**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@noerjeffries the exact limits are not documented and subject to change. For high level guidance and best practices on how to handle the errors please see the [Services Protocol](https://docs.microsoft.com/en-us/bingads/guides/services-protocol?view=bingads-12#throttling) doc. I hope this helps!
