### ISSUE TITLE
Example walkthrough code is unnecessarily verbose

### ISSUE THREAD

**Issue by jnalley** [MicrosoftDocs/BingAds-docs#346]
Hi, I think the code in many cases is unnecessarily verbose.  For example the function output_webfault_errors() could be written without repeating the same code blocks:

```
error_types = (
    ["ApiFault", "OperationErrors", "OperationError"],
    ["ApiFaultDetail", "Errors", "AdApiError"],
    ["ApiFaultDetail", "BatchErrors", "BatchError"],
    ["EditorialApiFaultDetail", "EditorialErrors", "EditorialError"],
    ["EditorialApiFaultDetail", "OperationErrors", "OperationError"],
    ["ExceptionDetail"],
)

def handle_error(detail, fields):
    api_errors = detail
    for field in fields:
        api_errors = getattr(api_errors, field, None)
    if api_errors is not None:
        if isinstance(api_errors, list):
            for api_error in api_errors:
                output_bing_ads_webfault_error(api_error)
        else:
            output_bing_ads_webfault_error(api_errors)
        return True
    return False


def output_webfault_errors(ex):
    if not hasattr(ex.fault, "detail"):
        raise Exception("Unknown WebFault")

    for et in error_types:
        if handle_error(ex.fault.detail, et):
            return

    raise Exception("Unknown WebFault")
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6b1a054-c617-7cd5-ff30-1608ee747756
* Version Independent ID: ff8c8e06-7ae0-b6a9-c9dc-4d4a534027a2
* Content: [Walkthrough: Bing Ads Desktop Application in Python - Bing Ads](https://docs.microsoft.com/en-us/bingads/guides/walkthrough-desktop-application-python?view=bingads-12#add-example-code)
* Content Source: [BingAds/bingads-12/guides/walkthrough-desktop-application-python.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/live/BingAds/bingads-12/guides/walkthrough-desktop-application-python.md)
* Service: **bing-ads**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@jnalley thanks for the suggestion! Will try it.

**Comment by eric-urban** [comment]
@jnalley with some modifications the doc is now updated. Thanks again for the suggestion.
