### ISSUE TITLE
Requesting Date

### ISSUE THREAD

**Issue by TobiGiese** [MicrosoftDocs/BingAds-docs#362]
Hello everyone,

I would like to include a date-column into my report, but unfortunately there is no valid request value "Date" I can request.
At some point I definately need to request historic data, such that a simple daily update in postprocessing is not possible. 
Is there a way around this? I apprechiate any help.

currently my output looks like this, and I simply want another column named date:

"Report Name: My Keyword Performance Report"
"Report Time: 8/27/2018"
"Time Zone: (GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna"
"Last Completed Available Day: 8/28/2018 2:05:00 PM (GMT)"
"Last Completed Available Hour: 8/28/2018 2:05:00 PM (GMT)"
"Report Aggregation: Daily"
"Report Filter: "
"Potential Incomplete Data: true"
"Rows: 3"

"AccountNumber","AccountId","CampaignId","DeviceType","Revenue","Impressions","Clicks","Spend","AverageCpc","Conversions"
"***","***","***","Computer","0.00","2","1","0.03","0.03","0"
"***","***","***","Computer","0.00","1","0","0.00","0.00","0"
"***","***","***","Computer","0.00","1","0","0.00","0.00","0"

"©2018 Microsoft Corporation. All rights reserved. "

Thanks Tobi

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea8dfe27-d24e-59cc-a4b5-7870536370be
* Version Independent ID: d1069843-3f3b-b538-a2cb-f0cca3805087
* Content: [Reporting Value Sets - Bing Ads](https://docs.microsoft.com/en-us/bingads/reporting-service/reporting-value-sets?view=bingads-12)
* Content Source: [BingAds/bingads-12/reporting-service/reporting-value-sets.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/live/BingAds/bingads-12/reporting-service/reporting-value-sets.md)
* Service: **bing-ads-reporting-service**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@TobiGiese you can include the TimePeriod column. For more details see [Time Period Column](https://docs.microsoft.com/en-us/bingads/guides/reports?view=bingads-12#timeperiod).
