### ISSUE TITLE
ClientSecret is not used in the code

### ISSUE THREAD

**Issue by pentium10** [MicrosoftDocs/BingAds-docs#368]
I am having problems getting an initial setup working. The ClientSecret field from AuthHelper is not used at all. Even If I delete it, the code doesn't crash. Also there are several missing informations, like how to obtain a ClientId and how to obtain a ClientSecret.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1bc63d1-9a2f-8428-5176-7b2faf6ab80e
* Version Independent ID: cdfa6e4f-a83c-4b20-1c35-77a72c61d348
* Content: [Walkthrough: Bing Ads Desktop Application in PHP - Bing Ads](https://docs.microsoft.com/en-us/bingads/guides/walkthrough-desktop-application-php?view=bingads-12)
* Content Source: [BingAds/bingads-12/guides/walkthrough-desktop-application-php.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/live/BingAds/bingads-12/guides/walkthrough-desktop-application-php.md)
* Service: **bing-ads**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@pentium10 per the doc:

> You must first [register an application](https://docs.microsoft.com/en-us/bingads/guides/authentication-oauth?view=bingads-12#registerapplication) and take note of the client ID. You'll also need your production [developer token](https://docs.microsoft.com/en-us/bingads/guides/get-started?view=bingads-12#get-developer-token).

Good feedback on the client secret. It isn't needed to run the samples locally. Thanks!

**Comment by pentium10** [comment]
How do we start without client secret? 

I went to https://apps.dev.microsoft.com
created an app, noted the application id

which is I think the Client ID, right please confirm?
Client ID = Application ID (please mention this on the docs page).

**Comment by pentium10** [comment]
further note, if you say you don't need ClientSecret, why the above fails?
also why in OAuthWithAuthorizationCode.php you have "->withClientSecret($this->ClientSecret)" and that's always NULL. I expect the SDK has serious flaws, and ClientSecret from AuthHelper is not getting propagated to this line.

**Comment by eric-urban** [comment]
Per the OAuth [guide](https://docs.microsoft.com/en-us/bingads/guides/authentication-oauth?view=bingads-12#registerapplication), clients running apps on services that span regions and devices such as Microsoft Azure should register a Web app with client secret. Since the sample does not use a client secret please try adding the Native platform (not web). We will also update the get started doc to clarify. The doc already maps application to client ID i.e., "edit the ClientId with the Application Id that was provisioned when you registered your application."

**Comment by pentium10** [comment]
I think I have everything setup, but still not working. 
I have a DeveloperToken pasted in AuthHelper.
I have an app from https://apps.dev.microsoft.com used application Id to client It in PHP.
Set the Environment to Production.
I added a native app to the above app. No value to copy paste to PHP. Do I need to copy something from the Native App screen?

When I start the code I get this:

```
$ php ReportRequests.php
Error: invalid_client
Description: The provided request must include a 'client_secret' input parameter.
```

I didn't do anything on Microsoft Azure. What shall I do on Azure? Do I need to obtain some key from there? I am willing to do a private video call to make this running smoothly. I am struggling since Friday.

**Comment by eric-urban** [comment]
@pentium10 do you still see Web platform via app registration? You might need to remove it. Can you share more details about your local environment and SDK version?

You should not need to do anything via Azure to run the samples. I mentioned it as an example scenario where you would register a web app with client secret.

**Comment by pentium10** [comment]
No I don't have anything else. This is the screen I have
from https://apps.dev.microsoft.com/

![image](https://user-images.githubusercontent.com/465691/45035795-84bc8b80-b063-11e8-8e7b-097cb4b57045.png)

**Comment by eric-urban** [comment]
@pentium10 I was able to repro the same error by adding https://login.live.com/oauth20_desktop.srf to the list of custom redirect URIs per your screen capture. The error message is not intuitive/helpful in this scenario, and I'll follow up with the identity team. In the meantime please try to remove https://login.live.com/oauth20_desktop.srf from the custom list and try again. It works when I only have *urn:ietf:wg:oauth:2.0:oob* and *https://login.microsoftonline.com/common/oauth2/nativeclient* in the list.

**Comment by pentium10** [comment]
@eric-urban still problems

I removed the uri from the native app section. BTW that is added automatically for you. 
The interface UX is extremely bad, you don't have a delete button etc...
You need to empty the field.

And after that I got this error:

```
$ php ReportRequests.php
You need to provide consent for the application to access your Bing Ads accounts. Copy and paste this authorization endpoint into a web browser and sign in with a Microsoft account with access to a Bing Ads account:

https://login.live.com/oauth20_authorize.srf?scope=bingads.manage&client_id=<edited>&response_type=code&redirect_uri=https://login.live.com/oauth20_desktop.srf

After you have granted consent in the web browser for the application to access your Bing Ads accounts, please enter the response URI that includes the authorization 'code' parameter:

https://login.live.com/oauth20_desktop.srf?code=<edited>&lc=1033


Last SOAP request/response:
Fault Code: s:Server
Fault String: Invalid client data. Check the SOAP fault details for more information
https://clientcenter.api.bingads.microsoft.com/Api/CustomerManagement/v12/CustomerManagementService.svc?singleWsdl
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns1="https://bingads.microsoft.com/Customer/v12"><SOAP-ENV:Header><ns1:CustomerAccountId/><ns1:Cust
omerId/><ns1:DeveloperToken><edited></ns1:DeveloperToken><ns1:UserName/><ns1:Password/><ns1:AuthenticationToken><edited></ns1:Authenticat
ionToken></SOAP-ENV:Header><SOAP-ENV:Body><ns1:GetUserRequest><ns1:UserId xsi:nil="true"/><ns1:IncludeLinkedAccountIds>true</ns1:IncludeLinkedAccountIds></ns1:GetUserRequest></SOAP-ENV:Body></SOAP-ENV:Envelope>

<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><s:Fault><faultcode>s:Server</faultcode><faultstring xml:lang="en-US">Invalid client data. Check the SOAP fault details for more information</faultstring><detail><Ad
ApiFaultDetail xmlns="https://adapi.microsoft.com" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><TrackingId>37fb3229-2b85-43aa-8cf0-974f3818ac10</TrackingId><Errors><AdApiError><Code>105</Code><Detail i:nil="true"/><ErrorCode>Inva
lidCredentials</ErrorCode><Message>Authentication failed. Either supplied credentials are invalid or the account is inactive</Message></AdApiError></Errors></AdApiFaultDetail></detail></s:Fault></s:Body></s:Envelope>

Fatal error: Class 'Microsoft\BingAds\Samples\V12\ReportingExampleHelper' not found in U:\fls_warehouse\bigquery\bingads\ReportRequests.php on line 141
```

I checked the account I have is super admin. 
Also checked the reporting example helper file is there, not sure why it's not locating it. 

Please advise what to do.

**Comment by pentium10** [comment]
It's unbelievable how inmature Bings Ads SDK and interface is. 

Now I have a crash on the page where Developer Tokens are visible. It persists, as it happens on FF, Chrome as well.

See the image:

![image](https://user-images.githubusercontent.com/465691/45075776-e70f9d80-b0f0-11e8-9261-cde5d09c5ee5.png)

Really really frustrating that you cannot get started with the SDK at all, it's either 
- wrong documentation (no details provided what a client id is)
- no details provided what a client secret is, why it's on the file, when it's used 
- if needed how to obtain client secret
- undocumented error that you cannot figure out why Native App has mislead to an error which you cannot control (totally blocked)
- UI interface is rudimentary, not 2018 style and not expecting something like this from Microsoft
- Error 105, undocumented, several guidance, but not sure how to go
- the Developer Token interface is broken
- no quick ability to switch between shells of different companies in the Developer Token interface
- chat support cannot tell you why this 500 http server side error happens 

Can you consolidate all these somewhere? As lots of people for sure they have frustrations.

**Comment by pentium10** [comment]
@eric-urban any feedback?

**Comment by eric-urban** [comment]
@pentium10 regarding the "Bing Ads Developer Center has encountered some problem while processing your request" error message, can you please share more details e.g., occurs when you arrived at the site and/or when you click on the Request a token button, or other? If the [support](https://advertise.bingads.microsoft.com/en-us/bing-ads-support) team did not answer your question on the spot via chat, please ask them to forward the question to our engineering team for further consultation. In the meantime if you prefer, please feel free to send detailed repro steps to me [directly](https://github.com/eric-urban).

As you observed we do not support switching customer context in the developer portal. This is the first time I've heard the request, although its a fair point i.e., makes sense to show all of the users that your Super Admin credentials can access. Can you share more details about the scenario and requirement? You could just get one developer token for use with any credentials (if upgraded to a universal developer token), in which case switching customer context in the developer portal might not be necessary. 

Regarding "undocumented error that you cannot figure out why Native App has mislead to an error which you cannot control (totally blocked)" I did follow up with the Microsoft identity team and this unexpected error impacts apps registered between August 30 - September 5th. It was not expected for this scenario, and the issue has been resolved going forward for all new apps that are registered. For apps created between August 30 - September 5th, the workaround is to delete the additional custom URIs as mentioned above. I also shared your feedback with the team regarding no 'x' or 'delete' button for the custom URIs. Thank you for that!

We do have documentation on client ID and client secret e.g., [here](https://docs.microsoft.com/en-us/bingads/guides/authentication-oauth?view=bingads-12) and [here](https://docs.microsoft.com/en-us/bingads/guides/sdk-authentication?view=bingads-12). There is opportunity to clarify i.e., add more details in the walkthrough. I will follow up on that part, before closing out this issue.

Best regards,
Eric

**Comment by pentium10** [comment]
as far I can tell, if I change the customer context on Bing Ads center, 
then go to this page by typing the url the page comes back with the errror

it's easy to reproduce:
1. go to https://developers.bingads.microsoft.com/Account
you see it's not the good context, then you go to switch context to step 2
2. get into: https://ui.bingads.microsoft.com/campaign/accountssummary?cid=4007549#customer/4007549/accounts-summary/performance
switch the customer account
3. go back to previous page, it crashed, 
4. switching context again, still crashed

you need to clear cookies or logout to get going again, and only works correctly for the 'default' account that's loading for you, but when you change contexts it stops working for all situations
I cannot access dev tokens only for the default page, not for other accounts.

as regarding client ID client Secret
you generally when you need to find something you search on the internet
when searching something you expect a clear page
like for example I was stucked to find a value to paste for client secret, and because of this I didn't read the entire page, so there should be a page which tells you when 

the simplest page that has how to obtain develoepr token link, then client id link, client secret link could actually help

also it would be good to mention what a native app is, what a web app is, what an api is good
as you probably stop reading the flow when you develop a Worker for a SDK data pull task

I think pages are too long, and there are no index pages, which could guide you to the right reading page

**Comment by eric-urban** [comment]
Closing the current issue since we have clarified details about ClientId in this doc. Dev portal feedback has been shared with the team.
