### ISSUE TITLE
Please reference possible error codes in Service Operation documentation.

### ISSUE THREAD

**Issue by khvn26** [MicrosoftDocs/BingAds-docs#382]
It would help massively not to guess/test which error codes which individual service operations can return.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f12121c1-58eb-b113-6522-e0380b04dcb7
* Version Independent ID: df47cf3c-eb8d-6de5-58d7-7f798687944e
* Content: [Bing Ads Operation Error Codes - Bing Ads](https://docs.microsoft.com/en-us/bingads/guides/operation-error-codes?view=bingads-12)
* Content Source: [BingAds/bingads-12/guides/operation-error-codes.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/live/BingAds/bingads-12/guides/operation-error-codes.md)
* Service: **bing-ads**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@khvn26 there isn't a strict contract for error codes to service operations. New error codes could be added in the future for an existing service operation. For details on the SOAP API fault model please see the [troubleshooting guide](https://docs.microsoft.com/en-us/bingads/guides/handle-service-errors-exceptions?view=bingads-12#faultoverview). Also note many of the same error codes are returned in the Bulk upload result file. For example 1042 can be returned whether creating ads via [AddAds](https://docs.microsoft.com/en-us/bingads/campaign-management-service/addads?view=bingads-12) or Bulk upload of an [Expanded Text Ad](https://docs.microsoft.com/en-us/bingads/bulk-service/expanded-text-ad?view=bingads-12) record.

**Comment by khvn26** [comment]
Thanks for the direction, I've overlooked the fault model doc.
