### ISSUE TITLE
We're unable to complete your request 

### ISSUE THREAD

**Issue by kakugiki** [MicrosoftDocs/BingAds-docs#387]
Copy and paste this authorization endpoint into a web browser and sign in with a Microsoft account with access to a Bing Ads account:

https://login.live-int.com/oauth20_authorize.srf?scope=bingads.manage&prompt=login&client_id=[myId]&response_type=code&redirect_uri=https://login.live-int.com/oauth20_desktop.srf

When I copied and pasted above link, I got this error:

We're unable to complete your request 

Microsoft account is experiencing technical problems. Please try again later.

**Comment by eric-urban** [comment]
@kakugiki I am not able to repro this issue. It may have been a temporary issue in the sandbox environment. To report service issues going forward I suggest that you please reach out via the [forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=BingAds) or [support](https://advertise.bingads.microsoft.com/en-us/bing-ads-support).
