### ISSUE TITLE
DELETED

### ISSUE THREAD

**Issue by cal97g** [MicrosoftDocs/BingAds-docs#414]
Microsoft website is misleading. Disguises a git issue as a comment. It's almost as intuitive as the python google ads 'sdk'.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3228ff4-34ac-a0b7-7091-f74212715a84
* Version Independent ID: dd837296-c1d9-6b03-d661-55112b5288bb
* Content: [Get Started Using Python with Bing Ads Services - Bing Ads](https://docs.microsoft.com/en-us/bingads/guides/get-started-python?view=bingads-12)
* Content Source: [BingAds/bingads-12/guides/get-started-python.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/live/BingAds/bingads-12/guides/get-started-python.md)
* Service: **bing-ads**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@cal97g please let me know if you have details about a specific scenario that we can help with. Thank you.

**Comment by cal97g** [comment]
Also highly unclear when I commented on the microsoft site that this would become an issue publicly visible on my Github profile.

**Comment by eric-urban** [comment]
@cal97g thanks for the feedback! For future reference the Github integration is mentioned next to the feedback button i.e., "Our new feedback system is built on GitHub Issues. Read about this change in [our blog post](https://docs.microsoft.com/teamblog/a-new-feedback-system-is-coming-to-docs)." 

I'll go ahead and close this issue as there is no specific documention request. Please feel free to reopen or contact support for SDK assistance via the [forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=BingAds) or [support link](http://go.microsoft.com/fwlink/?LinkId=269631).
