### ISSUE TITLE
"forty" misspelled as "fourty"

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/BingAds-docs#421]
This may be a product bug since it's described as enumeration values in some cases https://github.com/MicrosoftDocs/BingAds-docs/search?q=fourty&unscoped_q=fourty

**Comment by eric-urban** [comment]
@nschonni yes this is a known product bug. The doc reflects the value defined in the WSDL. We are evaluating whether to change it in v.next, although we are hesitant to make clients update their code over a spelling error. Since this is not a doc issue I'll go ahead and close this out. Thanks.
