### ISSUE TITLE
GetUserAsync is not responding

### ISSUE THREAD

**Issue by prathapnaidu** [MicrosoftDocs/BingAds-docs#424]
after user allowed the permissions while authentication, I got the access token and refresh token. Then I tried to get the user details like id using GetUserAsync call, but it is not responding for a long time..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 647ba7c0-26dc-94c8-80ad-c5650e4f761d
* Version Independent ID: be7a8696-014d-2e14-9f26-716f458dab8c
* Content: [Authentication With the SDKs - Bing Ads](https://docs.microsoft.com/en-us/bingads/guides/sdk-authentication?view=bingads-12)
* Content Source: [BingAds/bingads-12/guides/sdk-authentication.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/live/BingAds/bingads-12/guides/sdk-authentication.md)
* Service: **bing-ads**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
For assistance with this issue please raise a question via the [forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=BingAds) and/or [support](https://advertise.bingads.microsoft.com/en-us/bing-ads-support). Thank you.
