### ISSUE TITLE
Path1 and Path2 allows 52 characters, contradicting the documentation

### ISSUE THREAD

**Issue by hravnaas** [MicrosoftDocs/BingAds-docs#435]
Path1 and Path2 allows 52 characters, contradicting the documentation which is stating 50. For example, I can save this in Path1 and Path2 and received them calling the APIs:

{=COUNTDOWN("2019/02/17 00:00:00","en-US",3)} sabat"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 178a8ed3-db52-71e9-9c87-c717282aa64a
* Version Independent ID: fc2b6de0-e31e-e240-3691-0eb17803cc67
* Content: [ExpandedTextAd Data Object - Campaign Management - Bing Ads](https://docs.microsoft.com/en-us/bingads/campaign-management-service/expandedtextad?view=bingads-12)
* Content Source: [BingAds/bingads-12/campaign-management-service/expandedtextad.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/live/BingAds/bingads-12/campaign-management-service/expandedtextad.md)
* Service: **bing-ads-campaign-management-service**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@hravnaas per the documentation the entire countdown only counts as 8 characters against the post-substitution total of 15 e.g., this entire string counts as 8: "{=COUNTDOWN("2019/02/17 00:00:00","en-US",3)}". Your substituted total only uses 14 characters. Please let me know if this helps. We will also update the documentation to make it more clear.

**Comment by hravnaas** [comment]
Hi, @eric-urban. I'm not concerned with the post-substitution, only pre-substitution. Path1 and Path2 state "The maximum input length is 50 characters including dynamic text strings", but pulling down ads via the APIs and storing them in a local database we maintain, I see values up to 52 characters. The Bing Ads UI also allows 52 before it complains. Not a huge deal, but this might come back and bite others maintaining a local copy of the campaign structure, including ads.

Thanks,
Hans

**Comment by eric-urban** [comment]
@hravnaas I failed to mention that we also recently relaxed the pre-substitution limit from 50 to 1,000. The documentation will be updated to reflect this change as well. In my repro the UI complains about anything over 15 post-substutition e.g., "{=COUNTDOWN("2019/02/17 00:00:00","en-US",3)} 123456" is OK, but "{=COUNTDOWN("2019/02/17 00:00:00","en-US",3)} 1234567" is over the limit at 16 characters (8 for the countdown string and 8 for the remaining characters from space through the number 7.

**Comment by hravnaas** [comment]
@eric-urban - From the API side, will the change from 50 to 1000 be changed in the current v12 APIs or not until next version? This would be a breaking change.

**Comment by eric-urban** [comment]
@hravnaas I'm told that the change already occurred in v12. The max input length was increased (not restricted) from 50 to 1,000. I have not heard of any friction or anyone breaking by allowing extra characters. We have done this in the past from time to time e.g., to meet customer demand. We would not restrict the other way in the same API version though e.g., from 1,000 to 50.

**Comment by hravnaas** [comment]
@eric-urban If the API docs state 50, and the UI limits to 50, then modelling this in our own SQL database, we'd use a column of width 50. Also, our own Campaign Manager UI on top of that would be built to show a string of 50 in let's say an ad preview dialog. Unexpectedly received a 1000 character string, would most definitely be a breaking change, first resulting in a SQL exception. Should this happen today, well, we are in code freeze and can't deploy to production until January, so it could affect a number of merchants. Not good.

**Comment by eric-urban** [comment]
@hravnaas thanks for clarifying the scenario. I've shared this feedback with the team and will follow up with you. Please also note we increased the Text limit [from 80 to 90 characters last month](https://docs.microsoft.com/en-us/bingads/guides/release-notes?view=bingads-12#expandedtextads-october2018).

**Comment by hravnaas** [comment]
Thansk, @eric-urban, much appreciated.

**Comment by eric-urban** [comment]
@hravnaas we apologize for the inconvenience. We had not considered this a breaking change since the limit for add/update was relaxed (not constrained). However, we have taken the feedback that such a change should be considered more carefully and clients should be notified in advance. Please let me know if you have further questions or concerns. Thanks for your partnership!

**Comment by eric-urban** [comment]
@hravnaas the doc is updated so I'll close this doc issue. Thanks again

**Comment by hravnaas** [comment]
Thanks a lot for your help, @eric-urban
