### ISSUE TITLE
cannot get statistics in getstats

### ISSUE THREAD

**Issue by chiwan1526** [MicrosoftDocs/BingAds-docs#438]
cannot get statistics in getStats

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b8f824d-4040-0b6a-f882-c68a971e2221
* Version Independent ID: 02455ea6-931f-9955-9be0-73fa70a0597d
* Content: [Ad group script examples - Bing Ads](https://docs.microsoft.com/en-us/bingads/scripts/examples/)
* Content Source: [BingAds/scripts/examples/index.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/live/BingAds/scripts/examples/index.md)
* Service: **bingads-scripts**
* GitHub Login: @brapel
* Microsoft Alias: **v-brapel**

**Comment by swhite-msft** [comment]
Hello. Please provide more details, so we can assist you. Which example were you using, which entity are you not able to get stats from, etc. Thanks

**Comment by swhite-msft** [comment]
Closing due to lack of information.
