### ISSUE TITLE
.NET Framework Version

### ISSUE THREAD

**Issue by westmich** [MicrosoftDocs/BingAds-docs#487]
Did the target framework upgrade as well?  Not seeing any mention of this, but we are on version 4.5.2 and I get an error when trying to update through NuGet - 
"Could not install package 'System.Configuration.ConfigurationManager 4.4.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81988181-178d-abcd-1056-66ca14cdc4fb
* Version Independent ID: 51d5c971-07fa-e937-9c85-3f6ca6d7a228
* Content: [Migrate to Bing Ads API Version 12 - Bing Ads](https://docs.microsoft.com/en-us/bingads/guides/migration-guide?view=bingads-12)
* Content Source: [BingAds/bingads-12/guides/migration-guide.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/master/BingAds/bingads-12/guides/migration-guide.md)
* Service: **bing-ads**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@westmich not specific to version 12, the Bing Ads .NET SDK requirements are mentioned in [this blog article](https://blogs.msdn.microsoft.com/bing_ads_api/2018/04/20/sdk-support-for-api-v12-now-available/), and here in the [Get Started doc](https://docs.microsoft.com/en-us/bingads/guides/get-started-csharp?view=bingads-12#installation). I hope this helps!

**Comment by westmich** [comment]
Version 11 runs on .NET 4.5.2.  Version 12 will not.  If it is not specific to version 12 then how do I run version 12 on 4.5.2?

**Comment by eric-urban** [comment]
@westmich which SDK version are you using with 4.5.2? Are you by chance using 11.5.9 or earlier? I want to make sure I am not confusing you with SDK version versus API / service versions. Starting with SDK version 11.12.1 (supports both v11 and v12 services), 4.5.2 is not supported AFAIK. For a given SDK version e.g., 11.12.1 both service versions 11 and 12 should not differ with respect to .NET framework support.
