### ISSUE TITLE
Add 1263 - CampaignServiceCannotSetStartOrEndDateForAdRotation

### ISSUE THREAD

**Issue by khvn26** [MicrosoftDocs/BingAds-docs#510]
'Cannot set the Start or End Date of Ad Rotation feature for the ad group.'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f12121c1-58eb-b113-6522-e0380b04dcb7
* Version Independent ID: df47cf3c-eb8d-6de5-58d7-7f798687944e
* Content: [Bing Ads Operation Error Codes - Bing Ads](https://docs.microsoft.com/en-us/bingads/guides/operation-error-codes?view=bingads-12#1000)
* Content Source: [BingAds/bingads-12/guides/operation-error-codes.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/master/BingAds/bingads-12/guides/operation-error-codes.md)
* Service: **bing-ads**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@khvn26 thanks for letting us know! The doc is updated.
