### ISSUE TITLE
Microsoft account is experiencing technical problems. Please try again later. (obtaining WebAPI Auth Token)

### ISSUE THREAD

**Issue by jakeclutter** [MicrosoftDocs/BingAds-docs#520]
Hi! I've been attempting to shift a legacy service from Bing Ads V11 -&gt; V12 and I've run into difficulties generating the authentication token after registering our application. In particular since we are making a Web API and not a Web or Native app I am not sure what to enter as the `redirect_uri` parameter here:

`https://login.live.com/oauth20_authorize.srf?client_id=CLIENT_ID&scope=bingads.manage&response_type=code&redirect_uri=REDIRECTURI&state=ClientStateGoesHere`

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 616d9f7d-1fcb-3254-f059-79f451715eda
* Version Independent ID: e04a8424-8db2-13a8-6f12-f3b47f0f0362
* Content: [Bing Ads Web Service Addresses - Bing Ads](https://docs.microsoft.com/en-us/bingads/guides/web-service-addresses?view=bingads-12)
* Content Source: [BingAds/bingads-12/guides/web-service-addresses.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/master/BingAds/bingads-12/guides/web-service-addresses.md)
* Service: **bing-ads**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@jakeclutter - For your scenario, is the goal to secure your Web API with custom scopes as described [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-app-types#web-apis) and [here](https://github.com/azureadquickstarts/appmodelv2-nativeclient-dotnet)? If so, my understanding is that is beyond the scope of authenticating a Bing Ads user i.e., asking a Bing Ads user to consent to letting your app access their accounts (or granting the app access to your own accounts). For Bing Ads authentication where the OAuth scope is bingads.manage, you should register a web or native app depending in part on whether a client secret is needed. Please see [Authentication with OAuth](https://docs.microsoft.com/en-us/bingads/guides/authentication-oauth?view=bingads-12) for more details. For help with a specific error please feel free to share the repro steps in the [forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=BingAds) or via [support](https://advertise.bingads.microsoft.com/en-us/bing-ads-support). I hope this helps!
